language: c

dist: bionic

before_install:
  - export TERM=xterm
  - apt-get update -y
  - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
  - apt install bison build-essential curl flex git gnupg gperf ccache liblz4-tool libncurses5-dev libsdl1.2-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev build-essential kernel-package libncurses5-dev bzip2 git python wget gcc g++ curl sudo libssl-dev openssl -y
  - cd ~
  - mkdir clang && wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r428724.tar.gz -O clang.tar.gz && tar -xzf clang.tar.gz -C clang && rm clang.tar.gz
  - git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 --depth=1 toolchain
  - git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 --depth=1 toolchain-arm
  - git clone https://github.com/ucanchangetheworld/kernel_xiaomi_sm6250.git --depth=1 --branch=$TRAVIS_BRANCH kernel
  - git clone https://github.com/GeoZac/AnyKernel.git --depth=1 --branch=miatoll AnyKernel
  - export CROSS_COMPILE=$HOME/toolchain/bin/aarch64-linux-android-
  - export PATH="$HOME/clang/bin:$HOME/toolchain/bin:$HOME/toolchain-arm/bin:$PATH"
  - export ARCH=arm64
  - export SUBARCH=arm64
  - export KBUILD_BUILD_USER="GeoZac"
  - export KBUILD_BUILD_HOST="Travis"
  - cd ~/kernel
  - make clean && make mrproper O=output
  - make cust_defconfig O=output
  - make -j$(nproc --all) CC=clang LD=ld.lld CROSS_COMPILE=aarch64-linux-android- CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-androideabi- O=output

script:
  - export ARCH=arm64
  - export SUBARCH=arm64
  - export KBUILD_BUILD_USER="GeoZac"
  - export KBUILD_BUILD_HOST="Travis"
  - cd ~/kernel
  - make clean && make mrproper O=output
  - make cust_defconfig O=output
  - make -j$(nproc --all) CC=clang LD=ld.lld CROSS_COMPILE=aarch64-linux-android- CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-androideabi- O=output
