version: 2.1
jobs:
  Kernel_miatoll:
   docker:
      - image: dereference23/kernel_arm64:clang
   steps:
      - run:
          name: Prepare Environment
          no_output_timeout: 20m
          command: |
           export TERM=xterm
           ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

      - run:
          name: Downloading sources
          no_output_timeout: 20m
          command: |
            cd ~
            git clone https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git --depth=1 --branch=$CIRCLE_BRANCH kernel
            git clone https://github.com/GeoZac/AnyKernel.git --depth=1 --branch=miatoll AnyKernel

      - run:
          name: Compile
          no_output_timeout: 20m
          command: |
            echo 'export KBUILD_BUILD_USER="GeoZac"' >> $BASH_ENV
            echo 'export KBUILD_BUILD_HOST="CircleCI"' >> $BASH_ENV
            source $BASH_ENV
            cd ~/kernel
            make clean && make mrproper O=output
            make cust_defconfig O=out CC=clang
            make -j$(nproc --all) O=out CC=clang LD=ld.lld 

      - run:
          name: Check version
          no_output_timeout: 20m
          command: |
            cat ~/kernel/output/include/generated/compile.h

      - run:
          name: Send to telegram
          no_output_timeout: 20m
          command: |
            cd ~/AnyKernel
            cp ~/kernel/output/arch/arm64/boot/Image.gz-dtb .
            cp ~/kernel/output/arch/arm64/boot/dtbo.img .
            ZIPNAME="Kernel-$(date +%d_%m_%Y_%H_%M)-miatoll.zip"
            zip -r9 "${ZIPNAME}" ./* -x ".git/*" "README.md" ".gitignore" "*.zip"
            curl -F chat_id=$CHAT_ID -F document=@$ZIPNAME -F parse_mode=markdown https://api.telegram.org/bot$BOT_API_TOKEN/sendDocument

      - store_artifacts:
          path: ~/kernel/output/.config
          destination: kernel_defconfig

workflows:
  version: 2.1
  cooking:
    jobs:
      - Kernel_miatoll
